---

# Linux kernel configuration process, Kubernetes package installations and configurations

- include_tasks: sysctld.yml        
- include_tasks: repos.yml     
- include_tasks: runc.yml     
- include_tasks: containerd.yml     


- name: Instalando os pacotes necess√°rios
  apt:
    name: "{{ item }}"
  loop: "{{ k8s_packages }}"

- name: Mark hold no APT nos pacotes K8S
  shell: |
    apt-mark hold kubeadm kubectl kubelet containerd.io runc

...
